### ISSUE TITLE
IEDriverServer.exe 3.9.0.0 is detected as SONAR.Heuristic by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by KevinChrz** [SeriousM/WebDriver.IEDriverServer-nuget#17]
As of February 22, 2018 the file IEDriverServer.exe is flagging with Norton Symantec Endpoint Protection as Heur.AdvML.C with the following details:

Category: Malware
Sub category: Heuristic Virus
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Heur.AdvML.C
File: C:\PATHING\packages\Selenium.WebDriver.IEDriver.3.9.0\driver\IEDriverServer.exe
Location: Deleted or access blocked
Computer:
User: NETWORK SERVICE
Action taken: Cleaned by Deletion

![iedriverserver flag 01](https://user-images.githubusercontent.com/13453819/36595446-32bbde7a-1870-11e8-8f12-628dd395c02e.png)
![iedriverserver flag 02](https://user-images.githubusercontent.com/13453819/36595449-34247470-1870-11e8-8fe5-09d27a9147a4.png)

**Comment by KevinChrz** [comment]
...I will bring this issue up to Selenium, somehow..... closed the issue as it is not your code.

**Comment by SeriousM** [comment]
Thank you for reporting it anyway! I wasn't aware of this issue.
